name: deploy-container on push

on: # trigger on [push, workflow_dispatch]
  push:
    branches:
      - main
    paths:
      - 'projects/**'
  workflow_dispatch: # allow manual trigger workflow. Other: repository_dispatch (REST API trigger workflow), schedule (workflow is scheduled), workflow_call (can be called by other workflow) - github actions events

defaults:
  run:
    working-directory: projects/container

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build: # name of job
    runs-on: ubuntu-latest # env
    environment:
      name: github-pages

    steps: # key value pairs, step starts with `-`
#      - name: Output Github context
#        run: echo "${{ toJSON(github) }}" # GitHub action context, GitHub actions expressions

      - name: Checkout repository
        uses: actions/checkout@v4  # Uses existed GitHub Action | actions/checkout@v4 https://github.com/marketplace/actions/checkout

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Container - Install dependents and build
        run: |
          npm ci # ci - uses package-lock.json dependencies or use `npm install`
          npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

      - name: Marketing - Install dependents and build
        working-directory: projects/marketing
        run: |
          npm ci
          npm run build
        env:
            PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}
      - name: Marketing - move build files into 'container/latest/marketing/latest' directory
        working-directory: projects/marketing
        run: |
          ls dist/
          mv dist/* ../container/dist/container/latest

      - name: Dashboard - Install dependents and build
        working-directory: projects/dashboard
        run: |
          npm ci
          npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}
      - name: Dashboard - move build files into 'container/latest/marketing/latest' directory
        working-directory: projects/dashboard
        run: |
          ls dist/
          mv dist/* ../container/dist/container/latest

      - name: Auth - Install dependents and build
        working-directory: projects/auth
        run: |
          npm ci
          npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}
      - name: Auth - move build files into 'container/latest/auth/latest' directory
        working-directory: projects/auth
        run: |
          ls dist/
          mv dist/* ../container/dist/container/latest    

      - name: List generated files
        run: |
          ls dist/container/latest
          ls dist/container/latest/marketing/latest
          ls dist/container/latest/dashboard/latest
          ls dist/container/latest/auth/latest

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Load artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "projects/container/dist/container/latest/"  # or "build" for React

      - name: Deploy on GitHub Pages
        uses: actions/deploy-pages@v4