name: deploy-container on push

on: # trigger on [push, workflow_dispatch]
  push:
    branches:
      - main
    paths:
      - 'projects/container/**'
  workflow_dispatch: # allow manual trigger workflow. Other: repository_dispatch (REST API trigger workflow), schedule (workflow is scheduled), workflow_call (can be called by other workflow) - github actions events

defaults:
  run:
    working-directory: projects/container

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build: # name of job
    runs-on: ubuntu-latest # env
    environment:
      name: github-pages

    steps: # key value pairs, step starts with `-`
#      - name: Output Github context
#        run: echo "${{ toJSON(github) }}" # GitHub action context, GitHub actions expressions

      - name: Checkout repository
        uses: actions/checkout@v4  # Uses existed GitHub Action | actions/checkout@v4 https://github.com/marketplace/actions/checkout

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Marketing - Install dependents
        run: npm ci
        working-directory: projects/marketing

      - name: Marketing build
        run: npm run build
        working-directory: projects/marketing
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

      - name: Marketing - move build files into '/marketing/latest' directory
        run: |
            mkdir marketing
            cd marketing/
            mkdir latest/
            mv dist/* marketing/latest/

      - name: Dashboard - Install dependents
        run: npm ci
        working-directory: projects/dashboard

      - name: Dashboard build
        run: npm run build
        working-directory: projects/dashboard
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

      - name: Container - Install dependents
        run: npm ci # ci - uses package-lock.json dependencies or use `npm install`

      - name: Project build
        run: npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

      - name: List generated files
        run: |
              ls -la 
              ls -la dist
              ls -la dist/container
              ls -la dist/container/latest
              ls -la dist/marketing
              ls -la dist/marketing/latest
              ls -la dist/dashboard
              ls -la dist/dashboard/latest

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Load artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "projects/container/dist/"  # or "build" for React

      - name: Deploy on GitHub Pages
        uses: actions/deploy-pages@v4

#      - name: Configure AWS CLI (Official Action)
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1  # Change to your AWS region
#
#      - name: Sync `dist` folder to S3
#        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest

#      - uses: shinyinc/action-aws-cli@v1.2
#      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: ""
